[package]
name = "rust-simd"
version = "0.1.0"
authors = ["Rémi Garde <remi.garde@free.fr>"]
edition = "2018"
build = "build.rs"

[dependencies]
rand = "0.6"
lazy_static = "1.2"

[dev-dependencies]
criterion = "0.2"

[lib]
bench = false

[[bench]]
name = "bench"
harness = false
